name: "Terraform CI/CD - Prueba de WIF"

on:
  push:
    branches:
      - main
  workflow_dispatch: # Este botón nos permite ejecutarlo manualmente desde la web

# 
permissions:
  contents: read
  id-token: write

jobs:
  terraform-test:
    name: "Autenticación y Plan"
    runs-on: ubuntu-latest
    
    # 
    defaults:
      run:
        working-directory: ./01-bootstrap

    steps:
      - name: ⬇️ Checkout del código
        uses: actions/checkout@v4

      - name: 🔐 Autenticación en Google Cloud (Workload Identity)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/210029066248/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          		
          service_account: "github-actions-sa@open5gs-479200.iam.gserviceaccount.com"

      - name: 🛠️ Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: 🚀 Terraform Init
        run: terraform init

      - name: 🔍 Terraform Plan
        run: terraform plan
